spring.application.name=kabaadikart-backend
spring.data.mongodb.uri=mongodb://localhost:27017/Kabaadikart
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bharatpathania700@gmail.com
spring.mail.password=hgffqaiisydkytjl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.main.allow-bean-definition-overriding=true
